sudo: required

os:
  - linux

language: node_js

node_js:
  - '10'
  - '8'

before_install: # if "install" is overridden
  # Repo for Yarn
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
  - yarn global add greenkeeper-lockfile@1

script: yarn test --runInBand

branches:
  only:
    - master
    - /^greenkeeper/.*$/

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: never
    on_failure: change

services:
  - xvfb

before_script:
  - greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
