sudo: required

os:
  - linux

language: node_js

node_js:
  - '10'
  - '8'

branches:
  only:
    - master

cache: yarn

notifications:
  email:
    on_success: never
    on_failure: change

services:
  - xvfb
