build: off

os: unstable

platform:
  - x64

branches:
  only:
    - master

skip_tags: true

environment:
  nodejs_version: "10"

cache:
  - "%LOCALAPPDATA%\\Yarn"

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn install

test_script:
  - node --version
  - yarn --version
  - yarn test --runInBand